# Copyright (c) 2025 - 2026 Chair for Design Automation, TUM
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

"""Single-ion shuttling in a moving one-dimensional harmonic potential."""

from __future__ import annotations

from .model import (
    CoulombInteraction,
    Ion,
    MovingHarmonicPotential,
    Potential1D,
    ShuttlingConfig,
    ShuttlingResult,
    SpatialGrid,
    Trajectory,
    TwoIonInitialState,
    TwoIonShuttlingConfig,
    TwoIonShuttlingResult,
    quintic_trajectory,
)
from .ms_gate import (
    CollectiveMotionalState,
    MSGateConfig,
    MSPhaseSpaceLoop,
    MSGateResult,
    MotionalModeSpec,
    collective_diagonal_mixture,
    collective_fock_state,
    collective_ground_state,
    collective_state_from_two_ion_projection,
    collective_thermal_state,
    default_ms_modes,
    ms_phase_space_displacements,
    simulate_ms_gate,
)
from .simulation import simulate_shuttling
from .two_ion import CollectiveModeProjection, project_two_ion_state_to_collective_modes, simulate_two_ion_shuttling
from .visualization import (
    animate_pair_density,
    animate_two_ion_marginals,
    plot_center_of_mass_trace,
    plot_excess_energy_trace,
    plot_joint_mode_populations,
    plot_mean_separation_trace,
    plot_mode_excitation_trace,
    plot_mode_population_consistency,
    plot_mode_populations,
    plot_ms_fidelity,
    plot_ms_final_fidelities,
    plot_ms_mode_expectations,
    plot_ms_phase_space_loops,
    plot_ms_spin_populations,
    plot_momentum_trace,
    plot_normal_mode_phase_spaces,
    plot_pair_density_snapshot,
    plot_phase_space,
    plot_two_ion_marginal_trajectories,
    plot_two_ion_phase_space,
)

__all__ = [
    "CoulombInteraction",
    "CollectiveModeProjection",
    "CollectiveMotionalState",
    "Ion",
    "MSGateConfig",
    "MSPhaseSpaceLoop",
    "MSGateResult",
    "MovingHarmonicPotential",
    "MotionalModeSpec",
    "Potential1D",
    "ShuttlingConfig",
    "ShuttlingResult",
    "SpatialGrid",
    "Trajectory",
    "TwoIonInitialState",
    "TwoIonShuttlingConfig",
    "TwoIonShuttlingResult",
    "animate_pair_density",
    "animate_two_ion_marginals",
    "collective_diagonal_mixture",
    "collective_fock_state",
    "collective_ground_state",
    "collective_state_from_two_ion_projection",
    "collective_thermal_state",
    "default_ms_modes",
    "ms_phase_space_displacements",
    "quintic_trajectory",
    "plot_center_of_mass_trace",
    "plot_excess_energy_trace",
    "plot_joint_mode_populations",
    "plot_mean_separation_trace",
    "plot_mode_excitation_trace",
    "plot_mode_population_consistency",
    "plot_mode_populations",
    "plot_ms_fidelity",
    "plot_ms_final_fidelities",
    "plot_ms_mode_expectations",
    "plot_ms_phase_space_loops",
    "plot_ms_spin_populations",
    "plot_momentum_trace",
    "plot_normal_mode_phase_spaces",
    "plot_pair_density_snapshot",
    "plot_phase_space",
    "plot_two_ion_marginal_trajectories",
    "plot_two_ion_phase_space",
    "project_two_ion_state_to_collective_modes",
    "simulate_ms_gate",
    "simulate_shuttling",
    "simulate_two_ion_shuttling",
]
